version: 2
project_name: gbr

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz

checksum:
  name_template: checksums.txt

homebrew_casks:
  - repository:
      owner: Kadrian
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/Kadrian/gbr
    description: Switch git branch interactively using arrow keys
    license: MIT

aurs:
  - name: gbr-bin
    homepage: https://github.com/Kadrian/gbr
    description: Switch git branch interactively using arrow keys
    license: MIT
    private_key: ~/.ssh/aur
    maintainers:
      - Kai Rollmann
    git_url: ssh://aur@aur.archlinux.org/gbr-bin.git
    package: |
      install -Dm755 gbr "${pkgdir}/usr/bin/gbr"
